# Generated by Django 4.2.5 on 2023-09-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre del empleado')),
                ('apellido', models.CharField(max_length=40, verbose_name='Nombre del empleado')),
                ('cuil', models.CharField(max_length=15, verbose_name='CUIL del empleado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Empresa')),
                ('cuit', models.CharField(max_length=20, verbose_name='CUIT de la Empresa')),
                ('area', models.CharField(max_length=50, verbose_name='Area de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=40, verbose_name='Nombre del Servicio')),
                ('cantidad_empleados', models.IntegerField(verbose_name='cantidad de empleados')),
            ],
        ),
    ]
