# Generated by Django 4.2.5 on 2023-09-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido del empleado'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='cantidad_empleados',
            field=models.IntegerField(verbose_name='Cantidad de Empleados'),
        ),
    ]
