# Generated by Django 4.2.5 on 2023-09-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_empleados_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='cantidad_empleados',
            field=models.IntegerField(default=0),
        ),
    ]
